### ISSUE TITLE
retain_graph = True during backprop.

### ISSUE THREAD

**Issue by edorado93** [EagleW/Writing-editing-Network#3]
The entire Writing Editing Network is run everytime we have to generate a new abstract. Why then do we have to `retain_graph=True` during backpropagation. Won't that just add on to the memory footprint of the model?

Is there a specific reason for doing this?

**Comment by edorado93** [comment]
@EagleW ^

**Comment by EagleW** [comment]
@edorado93 Actually, we didn't treat one iteration as a model, instead, we treated decoder with several iterations as a whole model.

**Comment by edorado93** [comment]
Yes, I agree that's the formulation that would make sense. But from an implementation perspective, each iteration will generate the entire graph again. Isn't it?

**Comment by EagleW** [comment]
Yes, it seems to be that

**Comment by edorado93** [comment]
So, I can get rid of it and the model would still work? From the losses over an epoch, removing it doesn't seem to have any impact. I just wanted to confirm if there was indeed something specific this was added for that I might have missed.

**Comment by EagleW** [comment]
Yeah, I think so. But I think initially, I add it because it seems to produce some errors

**Comment by edorado93** [comment]
Hmmm. Cool. Thanks, @EagleW 👍 . I'll close the issue.
